#delimit ;
capture log close;
capture drop scode;

*log using "ts ccode, ISO to COW.log", replace;

*********************************************************************************;
*********************************************************************************;
*                                                                               *;
*   Andreas Beger                                                               *;
*   Florida State University                                                    *;
*   06 Jan. 2007                                                                *;
*                                                                               *;
*   File:       ts ccode, ISO to COW.do                                         *;
*   Purpose:    Create a variable containing numeric COW country codes in an    *;
*               existing cross-sectional dataset with ISO country codes.        *;
*               Covers time period from 1946 to 2004.                           *;
*   Input File: any .dta file, load before running this file                    *;
*   Log:        ts ccode, ISO to COW.log                                        *;
*   Note:       Rename the ISO state codes variable to 'siso'                   *;
*                                                                               *;
*********************************************************************************;
*********************************************************************************;
*                                                                               *;
*   Notes:                                                                      *;
*   (1) Before running this do file, load the dataset, and rename the ISO       *;
*       country code variable to "siso".                                        *;
*   (2) Variables:                                                              *;
*       scode   State Code (COW country code)                                   *;
*       siso    ISO State Code                                                  *;
*       year    Year variable                                                   *;
*   (3) This file is accurate for the time period from 1946 to 2004.            *;
*   (4) The specific name used for state/country in a dataset could be slightly *;
*       different from the one specific here.  In that case, you will either    *;
*       have to change the name used in this batch file or manually assign a    *;
*       country to that state/country in the dataset using STATA.               *;
*   (5) If you need a dataset that is consistent with the COW state membership, *;
*       you should merge the dataset you recoded with this do file with a       *;
*       dataset containing COW state membership data to ensure consistency.     *;
*       This do file will only correctly assign COW ccodes over time, but not   *;
*       drop any cases.                                                         *;
*   (6) Country codes are assigned according to the COW state membership list.  *;
*       Specific codings over time might be different in the dataset you are    *;
*       using, so verify cases in which there was a secession or unification.   *;
*                                                                               *;
*       Here is a list of the major changes of this kind:                       *;
*       Vietnamese unification - In 1975 North Vietnam (816, VNM/DRV) absorbs   *;
*       South Vietnam (817, RVN).                                               *;
*       German unification - On 03 October 1990, West Germany (260, GFR) and    *;
*       East Germany (265, GDR) are reunited as Germany (255, DEU/GER).         *;
*       USSR breakup -                                                          *;
*       Yugoslavia breakup - On 06 June 1991 (recognized 1992), Slovenia        *;
*       (349, SVN) seceeded from Yugoslavia (345, YUG). On 25 June 1991,        *;
*       Croatia (344, HRV) seceeded. On 08 September 1991, Macedonia (343, MKD) *;
*       seceeded (COW codes independence beg. 1993). Bosnia and Herzegovina     *;
*       (346, BIH seceeded between October 1991 (declaration of sovereignty),   *;
*       February/March 1992 (referendum), and 06 April 1992 (hostilities begin).*;
*       The remainder of Yugoslavia became the Federal Republic of Yugoslavia   *;
*       in 1992, which was renamed Serbia and Montenegro (SCG in PWT) in 2003.  *;
*       Czechoslovakia breakup - On 01 January 1993 Czechoslovakia (315, CZE)   *;
*       splits into Czech Republic (316, CZE) and Slovakia (317, SVK).          *;
*                                                                               *;
*********************************************************************************;

gen scode=.;

replace scode=  2 if siso=="USA";
replace scode= 20 if siso=="CAN";
replace scode= 31 if siso=="BHS";
replace scode= 40 if siso=="CUB";
replace scode= 41 if siso=="HTI";
replace scode= 42 if siso=="DOM";
replace scode= 51 if siso=="JAM";
replace scode= 52 if siso=="TTO";
replace scode= 53 if siso=="BRB";
replace scode= 54 if siso=="DMA";
replace scode= 55 if siso=="GRD";
replace scode= 56 if siso=="LCA";
replace scode= 57 if siso=="VCT";
replace scode= 58 if siso=="ATG";
replace scode= 60 if siso=="KNA";
replace scode= 70 if siso=="MEX";
replace scode= 80 if siso=="BLZ";
replace scode= 90 if siso=="GTM";
replace scode= 91 if siso=="HND";
replace scode= 92 if siso=="SLV";
replace scode= 93 if siso=="NIC";
replace scode= 94 if siso=="CRI";
replace scode= 95 if siso=="PAN";
replace scode=100 if siso=="COL";
replace scode=101 if siso=="VEN";
replace scode=110 if siso=="GUY";
replace scode=115 if siso=="SUR";
replace scode=130 if siso=="ECU";
replace scode=135 if siso=="PER";
replace scode=140 if siso=="BRA";
replace scode=145 if siso=="BOL";
replace scode=150 if siso=="PRY";
replace scode=155 if siso=="CHL";
replace scode=160 if siso=="ARG";
replace scode=165 if siso=="URY";
replace scode=200 if siso=="GBR";
replace scode=205 if siso=="IRL";
replace scode=210 if siso=="NLD";
replace scode=211 if siso=="BEL";
replace scode=212 if siso=="LUX";
replace scode=220 if siso=="FRA";
replace scode=221 if siso=="MCO";
replace scode=223 if siso=="LIE";
replace scode=225 if siso=="CHE";
replace scode=230 if siso=="ESP";
replace scode=232 if siso=="AND";
replace scode=235 if siso=="PRT";
replace scode=255 if siso=="DEU" & year>=1991;
replace scode=255 if siso=="GER" & year>=1991;
replace scode=260 if siso=="DEU" & year<=1990;
replace scode=260 if siso=="GER" & year<=1990;
replace scode=265 if siso=="GDR" & year<=1990;
replace scode=290 if siso=="POL";
replace scode=305 if siso=="AUT";
replace scode=310 if siso=="HUN";
*replace scode=315 if siso=="";
replace scode=316 if siso=="CZE";
replace scode=317 if siso=="SVK";
replace scode=325 if siso=="ITA";
replace scode=331 if siso=="SMR";
replace scode=338 if siso=="MLT";
replace scode=339 if siso=="ALB";
replace scode=343 if siso=="MKD" & year>=1993;
replace scode=344 if siso=="HRV" & year>=1992;
replace scode=345 if siso=="YUG";
replace scode=345 if siso=="SCG";
replace scode=346 if siso=="BIH" & year>=1992;
replace scode=349 if siso=="SVN" & year>=1992;
replace scode=350 if siso=="GRC";
replace scode=352 if siso=="CYP";
replace scode=355 if siso=="BGR";
replace scode=359 if siso=="MDA";
replace scode=360 if siso=="ROU";
replace scode=360 if siso=="ROM";
replace scode=365 if siso=="RUS";
replace scode=366 if siso=="EST";
replace scode=367 if siso=="LVA";
replace scode=368 if siso=="LTU";
replace scode=369 if siso=="UKR";
replace scode=370 if siso=="BLR";
replace scode=371 if siso=="ARM";
replace scode=372 if siso=="GEO";
replace scode=373 if siso=="AZE";
replace scode=375 if siso=="FIN";
replace scode=380 if siso=="SWE";
replace scode=385 if siso=="NOR";
replace scode=390 if siso=="DNK";
replace scode=395 if siso=="ISL";
replace scode=402 if siso=="CPV";
replace scode=403 if siso=="STP";
replace scode=404 if siso=="GNB";
replace scode=411 if siso=="GNQ";
replace scode=420 if siso=="GMB";
replace scode=432 if siso=="MLI";
replace scode=433 if siso=="SEN";
replace scode=434 if siso=="BEN";
replace scode=435 if siso=="MRT";
replace scode=436 if siso=="NER";
replace scode=437 if siso=="CIV";
replace scode=438 if siso=="GIN";
replace scode=439 if siso=="BFA";
replace scode=450 if siso=="LBR";
replace scode=451 if siso=="SLE";
replace scode=452 if siso=="GHA";
replace scode=461 if siso=="TGO";
replace scode=471 if siso=="CMR";
replace scode=475 if siso=="NGA";
replace scode=481 if siso=="GAB";
replace scode=482 if siso=="CAF";
replace scode=483 if siso=="TCD";
replace scode=484 if siso=="COG";
replace scode=490 if siso=="COD";
replace scode=490 if siso=="ZAR";
replace scode=500 if siso=="UGA";
replace scode=501 if siso=="KEN";
replace scode=510 if siso=="TZA";
*replace scode=511 if siso=="";
replace scode=516 if siso=="BDI";
replace scode=517 if siso=="RWA";
replace scode=520 if siso=="SOM";
replace scode=522 if siso=="DJI";
replace scode=530 if siso=="ETH";
replace scode=531 if siso=="ERI";
replace scode=540 if siso=="AGO";
replace scode=541 if siso=="MOZ";
replace scode=551 if siso=="ZMB";
replace scode=552 if siso=="ZWE";
replace scode=553 if siso=="MWI";
replace scode=560 if siso=="ZAF";
replace scode=565 if siso=="NAM";
replace scode=570 if siso=="LSO";
replace scode=571 if siso=="BWA";
replace scode=572 if siso=="SWZ";
replace scode=580 if siso=="MDG";
replace scode=581 if siso=="COM";
replace scode=590 if siso=="MUS";
replace scode=591 if siso=="SYC";
replace scode=600 if siso=="MAR";
replace scode=615 if siso=="DZA";
replace scode=616 if siso=="TUN";
replace scode=620 if siso=="LBY";
replace scode=625 if siso=="SDN";
replace scode=630 if siso=="IRN";
replace scode=640 if siso=="TUR";
replace scode=645 if siso=="IRQ";
replace scode=651 if siso=="EGY";
replace scode=652 if siso=="SYR";
replace scode=660 if siso=="LBN";
replace scode=663 if siso=="JOR";
replace scode=666 if siso=="ISR";
replace scode=670 if siso=="SAU";
*replace scode=678 if siso=="";
replace scode=679 if siso=="YEM";
*replace scode=680 if siso=="";
replace scode=690 if siso=="KWT";
replace scode=692 if siso=="BHR";
replace scode=694 if siso=="QAT";
replace scode=696 if siso=="ARE";
replace scode=698 if siso=="OMN";
replace scode=700 if siso=="AFG";
replace scode=701 if siso=="TKM";
replace scode=702 if siso=="TJK";
replace scode=703 if siso=="KGZ";
replace scode=704 if siso=="UZB";
replace scode=705 if siso=="KAZ";
replace scode=710 if siso=="CHN";
replace scode=712 if siso=="MNG";
replace scode=713 if siso=="TWN";
*replace scode=730 if siso=="";
replace scode=731 if siso=="PRK";
replace scode=732 if siso=="KOR";
replace scode=740 if siso=="JPN";
replace scode=750 if siso=="IND";
replace scode=760 if siso=="BTN";
replace scode=770 if siso=="PAK";
replace scode=771 if siso=="BGD";
replace scode=775 if siso=="MMR";
replace scode=780 if siso=="LKA";
replace scode=781 if siso=="MDV";
replace scode=790 if siso=="NPL";
replace scode=800 if siso=="THA";
replace scode=811 if siso=="KHM";
replace scode=812 if siso=="LAO";
replace scode=816 if siso=="VNM";
*replace scode=817 if siso=="";
replace scode=820 if siso=="MYS";
replace scode=830 if siso=="SGP";
replace scode=835 if siso=="BRN";
replace scode=840 if siso=="PHL";
replace scode=850 if siso=="IDN";
replace scode=860 if siso=="TLS";
replace scode=900 if siso=="AUS";
replace scode=910 if siso=="PNG";
replace scode=920 if siso=="NZL";
replace scode=935 if siso=="VUT";
replace scode=940 if siso=="SLB";
replace scode=946 if siso=="KIR";
replace scode=947 if siso=="TUV";
replace scode=950 if siso=="FJI";
replace scode=955 if siso=="TON";
replace scode=970 if siso=="NRU";
replace scode=983 if siso=="MHL";
replace scode=986 if siso=="PLW";
replace scode=987 if siso=="FSM";
replace scode=990 if siso=="WSM";

*log close;
;end